# Generated by Django 3.1.3 on 2022-04-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiperImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='gallery')),
                ('description', models.TextField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Фотографии для Карусели',
                'verbose_name_plural': 'Фотографии для Карусели',
            },
        ),
        migrations.DeleteModel(
            name='Swiper',
        ),
    ]
