# Generated by Django 3.1.3 on 2022-04-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220427_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='swiperimg',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='Название'),
        ),
    ]
