# Generated by Django 3.1.3 on 2022-04-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_swiperimg_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainNewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='gallery')),
                ('description', models.TextField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Пост на главной странице',
                'verbose_name_plural': 'Посты на главной странице',
            },
        ),
    ]
