# Generated by Django 3.1.3 on 2022-04-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_mainnewspost'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='Название')),
                ('description', models.TextField(max_length=100, verbose_name='Описание специальности')),
                ('img', models.ImageField(upload_to='gallery')),
                ('slug', models.SlugField(max_length=30)),
            ],
        ),
    ]
