# Generated by Django 3.1.3 on 2022-04-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_navbardropdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='gallery', verbose_name='Картинки')),
                ('description', models.TextField(default='', max_length=100, verbose_name='Описание')),
                ('title', models.CharField(default='', max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Информация на главной странице',
            },
        ),
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('number', models.IntegerField(max_length=10)),
            ],
            options={
                'verbose_name': 'Таблица с цифрами на главной странице',
            },
        ),
        migrations.CreateModel(
            name='NavbarDropdownAccept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='Название')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('img', models.ImageField(upload_to='gallery', verbose_name='Картинки')),
                ('slug', models.SlugField(max_length=30)),
            ],
            options={
                'verbose_name': 'Меню на главной странице',
            },
        ),
        migrations.CreateModel(
            name='NavbarDropdownColledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='Название')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('img', models.ImageField(upload_to='gallery', verbose_name='Картинки')),
                ('slug', models.SlugField(max_length=30)),
            ],
            options={
                'verbose_name': 'Меню на главной странице',
            },
        ),
        migrations.CreateModel(
            name='NavbarDropdownDigitarium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='Название')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('img', models.ImageField(upload_to='gallery', verbose_name='Картинки')),
                ('slug', models.SlugField(max_length=30)),
            ],
            options={
                'verbose_name': 'Меню на главной странице',
            },
        ),
        migrations.CreateModel(
            name='NavbarDropdownParents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='Название')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('img', models.ImageField(upload_to='gallery', verbose_name='Картинки')),
                ('slug', models.SlugField(max_length=30)),
            ],
            options={
                'verbose_name': 'Меню на главной странице',
            },
        ),
        migrations.CreateModel(
            name='NavbarDropdownSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='Название')),
                ('description', models.TextField(max_length=100, verbose_name='Описание специальности')),
                ('img', models.ImageField(upload_to='gallery', verbose_name='Картинки')),
                ('slug', models.SlugField(max_length=30)),
            ],
            options={
                'verbose_name': 'Меню на главной странице',
            },
        ),
        migrations.CreateModel(
            name='NavbarDropdownStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='Название')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('img', models.ImageField(upload_to='gallery', verbose_name='Картинки')),
                ('slug', models.SlugField(max_length=30)),
            ],
            options={
                'verbose_name': 'Меню на главной странице',
            },
        ),
        migrations.DeleteModel(
            name='NavbarDropdown',
        ),
    ]
