# Generated by Django 3.1.3 on 2022-04-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_mainpostsecond'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutuniverse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
            ],
        ),
    ]
