# Generated by Django 3.1.3 on 2022-04-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_aboutuniverse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForParents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Ата аналарга',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutuniverse',
            options={'verbose_name': 'Про колледж'},
        ),
        migrations.AlterModelOptions(
            name='navbardropdownaccept',
            options={'verbose_name': 'Кабылдау'},
        ),
        migrations.AlterModelOptions(
            name='navbardropdowncolledge',
            options={'verbose_name': 'Колледж'},
        ),
        migrations.AlterModelOptions(
            name='navbardropdowndigitarium',
            options={'verbose_name': 'Digitarium'},
        ),
        migrations.AlterModelOptions(
            name='navbardropdownparents',
            options={'verbose_name': 'Ата аналарга'},
        ),
        migrations.AlterModelOptions(
            name='navbardropdownspeciality',
            options={'verbose_name': 'Мамандык'},
        ),
        migrations.AlterModelOptions(
            name='navbardropdownstudents',
            options={'verbose_name': 'Студенттерге'},
        ),
    ]
